import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :soundboard, SoundboardWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Soundboard.Finch

config :soundboard, Soundboard.Repo,
  database: "/app/priv/static/uploads/soundboard_prod.db",
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# Ensure the uploads directory exists
config :soundboard,
  upload_directory: "/app/priv/static/uploads"

config :soundboard,
  env: :prod

# Configure logging for production - enable debug level for voice troubleshooting
config :logger, level: :debug

# Nostrum configuration for stable audio playback
config :nostrum,
  youtubedl: nil,
  streamlink: nil,
  ffmpeg: "/usr/bin/ffmpeg",
  # 20 frames (400ms) is more stable for network jitter and VM Docker jitter
  # Default is 10, but 20 provides better stability for soundboards
  # Only use 1 for ultra-short sounds (< 200ms) that sometimes get swallowed
  audio_frames_per_burst: 20,
  # Increased timeout for more reliable connection handling
  audio_timeout: 30_000
